### ISSUE TITLE
Allow for all Misskey/Calckey servers

### ISSUE THREAD

**Issue by ThatOneCalculator** [ikakonbu/Misskey-TL-Filter#1]
You just have to check if the document has `#misskey_app` or `#calckey_app`, that way it can work on instances other than .io

**Comment by ikakonbu** [comment]
Thanks for the suggestion.
I once considered the idea of having it work on all misskey instances, but considering that we use CSS for filtering and each site has slightly different CSS to meet their requirements, we are currently working only on misskey.io.
(In the past, when I introduced my own CSS on nijimiss.moe, it did not work correctly and I had to modify the code.)

If we want it to work on all instances, we would not guarantee it to work on anything other than misskey.io, Or, we would allow each user to customize the CSS used for filtering (so that it can be applied in each instance).

**Comment by ikakonbu** [comment]
After some thought, I decided to allow this extension to run on other servers.
We will allow it by writing the server URL we want it to work on in the settings field
(However, it is impossible to check that it works on all misskey servers, so we do not guarantee that it will work perfectly on any server other than misskey.io)
![image](https://github.com/ikakonbu/Misskey-TL-Filter/assets/82440954/a6b5095e-780d-4735-a0d6-a4a2866c2be9)
